### ISSUE TITLE
Linkerman v0.1.1 Error: Functions not disabled in php.ini. Add in file: C:\laragon\www\yiishop\php.ini

### ISSUE THREAD

**Issue by spicytuna8** [zhanguangcheng/yii2-workerman#1]
hi, i follow the instruction, im using windows on my local using laragon

![image](https://github.com/zhanguangcheng/yii2-workerman/assets/9192757/49d93bbb-b8a9-421b-b699-73f6c24ad4db)

is it any instructions missed?
thanks

**Comment by zhanguangcheng** [comment]
> hi, i follow the instruction, im using windows on my local using laragon
> 
> ![image](https://private-user-images.githubusercontent.com/9192757/289098330-49d93bbb-b8a9-421b-b699-73f6c24ad4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNTI4MjUsIm5iZiI6MTcwMjA1MjUyNSwicGF0aCI6Ii85MTkyNzU3LzI4OTA5ODMzMC00OWQ5M2JiYi1iOGE5LTQyMWItYjY5OS03M2Y2YzI0YWQ0ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMTYyMjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTczNDQzOThjODNmNDM4ZmFhNmJlY2VjMmU5MjVlMjI0MTNkZDY4OTk2ZjdiMDJkMjA5OGUxZGYzNWJkZDgxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zHy7t2dEZOSc9hSxjfIeUps6oR4Ec1FCFwBUMIRR4sA)
> 
> is it any instructions missed? thanks

Hi, in Windows systems, you can try the following:
1. Find the installation path for PHP on your computer and add the configuration to the php.ini file
for example:`C:\laragon\bin\php\php-8.1.10-Win32-vs16-x64\php.ini`
```ini
disable_functions=set_time_limit,header,header_remove,headers_sent,headers_list,http_response_code,setcookie,setrawcookie,session_start,session_write_close,session_status,session_id,session_name,session_save_path,session_regenerate_id,session_unset,session_destroy
```

3. Execute Command
```bash
php server.php start
```

In addition, I have updated the code and optimized the project template. You can try using the latest version

**Comment by spicytuna8** [comment]
thanks it works!

i saw, $worker->count = 12; at server.php. Is the function the same as a workerman, running multiple worker processes concurrently.

can i just use workerman config forexample the ssl certificate config & running with daemon mode at ubuntu server
php server.php start -d
like this? 
thanks

**Comment by zhanguangcheng** [comment]
Yes, it is fully compatible with workerman.

**Comment by spicytuna8** [comment]
very nice, thx for your work.
btw how to use monitor.php, i hope you add some instruction :D, 
many thanks

**Comment by zhanguangcheng** [comment]
The function of monitor.php is to automatically reload code after modification. It only supports Linux systems(Recommend using WSL), and need inotify extension, and more: https://www.workerman.net/doc/workerman/components/file-monitor.html

**Comment by spicytuna8** [comment]
Oo ok, thanks for your reference
