### ISSUE TITLE
Warning: Packetsoutoforder.Expected1received0.Packetsize=145in

### ISSUE THREAD

**Issue by spicytuna8** [zhanguangcheng/yii2-workerman#2]
![image](https://github.com/zhanguangcheng/yii2-workerman/assets/9192757/6b8595c2-8a33-4246-a947-40bd76b260bc)
is it normal ?, so i just need to remove warning at php.ini error reporting right ?

**Comment by zhanguangcheng** [comment]
Add configuration to MySQL configuration file and restart MySQL
```ini
[mysqld]

max_allowed_packet=64M
```

**Comment by spicytuna8** [comment]
ok,
