### ISSUE TITLE
don't want to use Redis at all 

### ISSUE THREAD

**Issue by spicytuna8** [zhanguangcheng/yii2-workerman#4]
sorry to bother you again, Is there any configuration if I don't want to use Redis at all?
thanks

**Comment by zhanguangcheng** [comment]
it's ok, delete these codes to disable Redis
https://github.com/zhanguangcheng/yii2-workerman/blob/master/server.php#L30-L38
https://github.com/zhanguangcheng/yii2-workerman/blob/master/config/web.php#L41-L48

**Comment by spicytuna8** [comment]
ok great
