### ISSUE TITLE
best practice for keep alive or monitor the workerman

### ISSUE THREAD

**Issue by spicytuna8** [zhanguangcheng/yii2-workerman#5]
hi @zhanguangcheng me again, 
do you have any suggestion best practice for handle the workerman keep alive when the vps restart or something, maybe using nohub, supervisor, or create service, and how we can use the heartbeat for live indicator, i saw walkor create ping/pong
https://github.com/walkor/Workerman/issues/324#issuecomment-387398035
If client send ping then workerman(as websocket server) will send pong automatically.

thanks in advanced

**Comment by zhanguangcheng** [comment]
Using Systemd to manage Workerman services, an example of Workerman's service configuration file:

/usr/lib/systemd/system/workerman.service
```ini
[Unit]
Description=workerman
After=network.target

[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/bin/php /var/www/app/server.php start -d
ExecReload=/usr/bin/php /var/www/app/server.php reload -d
ExecStop=/usr/bin/php /var/www/app/server.php stop
Restart=on-failure
RestartSec=20s
PrivateTmp=true
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

service start
```bash
systemctl start workerman.service
```

auto start
```bash
systemctl enable workerman.service
```

**Comment by spicytuna8** [comment]
thank you
